<%@ Page Title="Contact" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="DiarySaintFaustina.aspx.cs" Inherits="DoSłówekProjekt.Contact" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <hgroup class="title">
        <h1><%: Title %>.</h1>
        <h2>Your contact page.</h2>
    </hgroup>

    <section class="contact">
        <header>
            <h3>Phone:</h3>
        </header>
        <p>
            <span class="label">Main:</span>
            <span>425.555.0100</span>
        </p>
        <p>
            <span class="label">After Hours:</span>
            <span>425.555.0199</span>
        </p>
    </section>

    <section class="contact">
        
            <h3>/////////
Preface
The diary of [Saint Maria] Faustina is the record of her life experience – the journey of her soul. She was graced by a special communion with God, and the diary expresses her conviction that communion ought to be the center of our lives. Since the 1940?s, the Marians of the Immaculate Conception, St. Stanislaus Kostka Province, have shared this conviction and have undertaken the promulgation of God?s mercy throughout the world, particularly as it has been proclaimed by [Saint] Faustina.
3
In 1979, convinced of the importance of the diary, the Marians were instrumental in bringing it – in its rough typewritten form – out of Poland. We made the necessary corrections to the manuscript and published a critical Polish edition that has been promulgated throughout the world to Polish speaking people.
At the same time, we commissioned a couple in Poland, Adam and Danuta Pasicki, to translate the diary into English. Once they had completed this first, literal translation we asked Archbishop George Pearce, S.M., to re-translate portions of it in accordance with proper English terminology for the various theological concepts and spiritual experiences referred to throughout the diary. Archbishop Pearce was supported in this second translation by Fathers George Kosicki, C.S.B., Gerald Farrell, M.M., Leo McCauley, S.J., and an Oblate, Francis Bagan, O.M.I.
When this text was completed, it was given to Father Seraphim Michalenko, M.I.C., who was Director of the Divine Mercy Department from 1979-1986. Together with Sister Sophia Michalenko, C.M.G.T., he carefully reviewed the translation, often referring back to the original Polish to ensure exactness of expression. Father Joseph Sielski, M.I.C., and Father Kazimierz Chwalek, M.I.C., were then asked to review the text, re-reading it for authentic agreement with the Polish.
Finally, in the first part of 1987, the text was returned to the Divine Mercy Department, [then] headed by Father George Kosicki, C.S.B. Through his efforts, the tireless work of Sister Sophia Michalenko, C.M.G.T., and the assistance of Vincent Flynn, the diary was subjected to a complete editing, re-typing, and proofing process for clarity of expression and readability according to current English grammar and usage. The index, listing the main themes of the diary, was compiled by Father Eugene Ozimek and developed by Fr. George Kosicki and Sister Sophia. The design, composition, and mechanicals were then completed by Charles Parise and Pat Menatti, and the diary was printed by the Marian Press at the Marian Helpers Center. To all involved with this work, we wish to express our deepest gratitude and the assurance of our prayers.

///////
Since the polish diary is the official text, we have made every effort to be truly faithful to it, and to retain the variousl shades of meaning implied in the theological and spiritual terms used by [Saint] Faustina – a definite challenge, indeed! In translating the diary, we dealt with the same kind of challenge that faces the translators of Sacred Scripture. Some terms allow for a variety of expressions even though the meanings are the same, and the final translation thus becomes a personal choice of style and expression on the part of the translator.
For the most part, the texts that have already been published in the popular devotional booklets are the same as those used in the diary, though in some instances, there again may be slight differences of style and expression.
Special Features of this New English Edition
In the final editing process, inconsistencies of verb tense, capitalization, and punctuation were standardized as much as possible without losing [Saint] Faustina?s unique style and powerful simplicity of expression. Our Lord?s words to [Saint] Faustina were set in bold type for emphasis, while Our Lady?s words were set in italics. The page numbers of
4
[Saint] Faustina?s original notebooks were also set in bold type, and paragraphs thought to be overly long or diversified in content were split into shorter paragraph units for readability.
The footnotes, too, have been reexamined, and additional clarifying notes have been added where necessary. Notes that were no longer pertinent, in light of changes incorporated into the English translation, were deleted; and, wherever possible, explanatory notes were placed in [square brackets] in the text itself to avoid unnecessary breaks in the reading.
Our deepest hope is that this diary may truly be a vehicle of grace for all who read it, for in reading it we can see that the mercy of God lives forever. Above, all, we hope that all people will be struck by the truth that mankind will not have peace until it turns with trust to God?s mercy.
May each one of you experience the power of the Blood and Water that poured out from the Heart of Jesus as a fount of mercy, and may each of you find confidence and trust in this ever-present mercy of God! //////
Gratefully in the Lord,
Very Rev. Richard J. Drabik, M.I.C.
Provincial Superior
Eden Hill, Stockbridge, Massachusetts
March 19, 1987
PREFACE
ORIGINAL PREFACE TO THE POLISH EDITION, 1981
In presenting this edition of the Dairy of [Saint] Maria Faustina Kowalska I am fully aware that I am introducing a document of Catholic mysticism of exceptional worth, not only for the Church in Poland, but also for the Universal Church. This publication is the critical edition, and thus reliable. It is the work of the Postulator of Sister Faustina, under the direction of the authority of the Archdiocese of Cracow.
The Diary, whose object is devotion to The Divine Mercy, has acquired tremendous interest lately for two reasons:
Firstly: The Sacred Congregation for the Doctrine of the Faith, in its revision more than two years ago [1978], withdrew the censures and reservations advanced earlier by the Holy See in relation to the writings of Sister Faustina. The withdrawal of the “Notification” caused the devotion to The Divine Mercy, as presented in the Diary, to grow in renewed vitality on all continents, as is
5
evidenced by the numerous testimonies received by the Postulator and the Congregation of which Sister Faustina was a member.
Secondly: The recent encyclical of Pope John Paul II, Dives in Misericordia, happily fixed the attention of the Church, and even of the secular world, on this most wonderful attribute of God and extraordinary aspect of the economy of salvation, which is The Divine Mercy.
A comprehensive study in order to indicate the affinity of ideas found in the Diary of [Saint] Maria Faustina and this encyclical (not to mention their probably interdependence) would be most welcome. These salient points certainly are numerous, for they draw their inspiration from the same source; namely, from the revelation of God and the teaching of Christ.
Furthermore, they come from the same spiritual environment, from Cracow, the city which, as far as I know, possesses the oldest church dedicated to the honor of The Divine Mercy. It is likewise necessary to stress that it was Karol Cardinal Wojtyla, the Archbishop of Cracow at that time, who made efforts to begin The Process of Beatification of Sister Faustina Kowalska and did inaugurate that process.////////////
In this light, the Diary of [Saint] Maria Faustina took on exceptional meaning for Catholic spirituality; and that is why it was fitting to prepare a credible edition, in order to prevent the distortion of the text by persons who perhaps are acting in good faith, but who are not adequately prepared for such work. Thus, publications containing differences and even contradictions, such as took place with the spiritual diary of St. Therese of the Child Jesus, The Story of a Soul, can be avoided.
The reader, after just a superficial skimming of the Diary, may be struck by the simplicity of the language and even by the spelling and stylistic errors, but he should not forget that the author of the Diary had but a limited elementary education. The theology alone which is found in the Diary awakens in the reader a conviction of its uniqueness; and if one considers the contrast between [Saint] Faustina’s education and the loftiness of her theology, the contrast alone indicates the special influence of Divine Grace.
I would like to mention here my meeting with a well-known contemporary mystic, Sister Speranza, who in Collevalenza, not far from Todi [Italy], founded the sanctuary of “The Most Merciful Love,” the site of numerous pilgrimages. I asked Sister Speranza whether she had heard of the writings of Sister Faustina and what she thought of them. She answered me with simplicity: “The writings contain a wonderful teaching, but reading them one must remember that God speaks to philosophers in the language of philosophers and to simple souls in the language of simple ones, and only to these last does He reveal truths hidden from the wise and prudent of this world.”
/////////
To conclude this preface, permit me to mention yet one more personal recollection from the year 1952, when for the first time I took part in a solemn beatification ceremony in St. Peter’s Basilica. After the festivity, I was asked by some person who also participated, “Who exactly was this blessed one?” The question embarrassed me very much, because at the moment I could not recall who those blessed were, although I knew full well that the real purpose of a beatification is to present to the people of God a model to consider and imitate in their lives.
Among the candidates for beatification and canonization Poland has presently two persons familiar to the whole world which knows who they are, what they accomplished in their lifetime and what sort of message their lives proclaim. They are Blessed [now Saint] Maximilian
6
Kolbe, the martyr of love, and Sister [now Saint] Faustina Kowalska, the Apostle of The Divine Mercy.
Rome, December 20, 1980
+ Andrew M. Deskur
Titular Archbishop of Tene
.
INTRODUCTION
1. Saint Maria Faustina Kowalska, known today the world over as the “Apostle of the Divine Mercy,” is numbered by theologians among the outstanding mystics of the Church.
She was the third of ten children born into a poor and pious peasant family
in Glogowiec, a village in the heart of Poland. At her baptism in the nearby Parish Church of Swinice Warckie she was given the name “Helena.” From childhood she distinguished herself by her piety, love of prayer, industriousness and obedience as well as by her great sensitivity to human misery. She had hardly three years of schooling, and at the age of fourteen she left the family hearth to help her parents and to earn her own livelihood serving as a domestic in the nearby cities of Aleksandrów and Lódz.///////////
When she was only seven (two years before her First Holy Communion), Helen already sensed in her soul the call to embrace the religious life. When later she made her desire known to her parents, they categorically did not acquiesce in her entering a convent. Because of this situation Helen strove to stifle this divine call within her. Pressed on, however, by a vision of the suffering Christ and by the words of His reproach: “How long shall I put up with you and how long will you keep putting Me off?” (Diary, 9), she bagan to search for a convent to join. She knocked on many a convent door, but nowhere was she accepted. Finally on August 1, 1925, Helen crossed the threshold of the cloister in the convent of the Congregation of Sisters of Our Lady of Mercy on Zytnia Street in Warsaw. In her Diary she declared: “It seemed to me that I had stepped into the life of Paradise. A single prayer was bursting forth from my heart, one of thanksgiving” (Diary, 17).
After a few weeks she experienced nonetheless a strong temptation to transfer to a different congregation in which there would be more time for prayer. It was then the Lord Jesus, manifesting to her His wounded and tortured face, said: “It is you who will cause Me
///////////
7
this pain if you leave this convent. It is to this place that I called you and nowhere else, and [it is here] I have prepared many graces for you” (Diary, 19).
Upon her entrance to the Congregation Helen received the name Sr. Maria Faustina. Her novitiate she spent in Cracow, and there, in the presence of Bishop Stanislaus Rospond, she pronounced her first religious vows, and five years later, she made her perpetual profession of the vows of chastity, poverty and obedience. She was assigned to work in a number of the Congregation?s houses, but for a longer period in those of Cracow, Plock and Vilnius, fulfilling the duties of cook, gardener and doorkeeper.
To all external appearances nothing betrayed her extraordinarily rich mystical life. She zealously went about her duties, she faithfully observed all the religious rules, she was recollected and kept silent, all the while being natural, cheerful, full of kindness and of unselfish love of neighbor.
Her entire life was concentrated on constant striving for an even fuller union with God and on self-sacrificing cooperation with Jesus in the work of saving souls. “My Jesus” – she avowed in her Diary - “You know that from my earliest years I have wanted to become a great saint; that is to say, I have wanted to love You with a love so great that there would be no soul who has hitherto loved You so” (Diary, 1372).////////////
It is her Diary that reveals to us the depths of her spiritual life. An attentive reading of these records offers a picture of the high degree of her soul?s union with God – the great extent of God?s company keeping with her soul, as well as her efforts and struggles on the way to Christian perfection. The Lord endowed her with great graces – with the gift of contemplation, with a deep knowledge of the mystery of the mercy of God, wish visions, revelations, the hidden stigmata, with the gift of prophecy and of reading into human souls, and also with the rare gift of mystical espousals. As lavishly gifted as she was, this is what she wrote: “Neither graces, nor revelations, nor raptures, nor gifts granted to a soul make it perfect, but rather the intimate union of the soul with God. …….My sanctity and perfection is based upon the close union of my will with the will of God” (Diary, 1107).
The austere lifestyle and exhausting fasts that she imposed upon herself even before joining the Congregation, weakened her organism to such an extent that already during her postulantship it became necessary to send her to Skolimów near Warsaw to restore her to health. Towards the end of her first year of novitiate, she was visited by unusually painful mystical experiences of the so-called dark night, and later by the spiritual and moral sufferings related to the accomplishment of the mission she was receiving from Christ the Lord. [St.] Faustina laid down her life in sacrifice for sinners and on this account she also sustained diverse sufferings, in order by means of them to come to the aid of their souls. During the last years of her life, inner sufferings of the so-called “passive night” of the soul and bodily diseases grew in intensity. The spreading tuberculosis attached her lungs and alimentary canal. For this reason, twice she underwent several months? treatment in the hospital on Pradnik Street in Cracow.
Physically ravaged, but fully mature spiritually, she died in the opinion of sanctity, mystically united with God, on October 5, 1938, hardly 33 years old, having been a religious for 13 years. Her mortal remains were laid to rest in the common tomb in the convent?s cemetery in Cracow-Lagiewniki. In 1966, during the informative process towards Sister Faustina?s beatification, they were transferred to the convent chapel.////////////
8
To this simple, uneducated, but courageous woman religious, who trusted Him without limit, Our Lord Jesus consigned the great mission to proclaim His message of mercy directed to the whole world: “Today,” He told her, “I am sending you with My mercy to the people of the whole world. I do not want to punish aching mankind, but I desire to heal it, pressing it to My merciful Heart” (Diary, 1588). You are the secretary of My mercy; I have chosen you for that office in this and the next life” (Diary, 1605) …… “to make known to souls the great mercy that I have for them, and to exhort them to trust in the bottomless depth of My mercy” (Diary, 1567).
2. ST. FAUSTINA?S MISSION. In short, her mission consists in reminding us of the immemorial, but seemingly forgotten, truths of our faith about God?s merciful love for men, and in conveying to us new forms of devotion to The Divine Mercy, the practice of which is to lead to the revival of the spiritual life in the spirit of Christian trust and mercy.
St. Faustina?s Diary, which Jesus Christ ordered her to keep during the last four years of her life, is a kind of journal in which the author recorded current or retrospective events related primarily to the “encounters” of her soul with God. A rigorous, scholarly analysis of her notebooks was necessary to extract from them everything which is considered essential to her mission. //////////
This work was accomplished by an eminent and highly esteemed theologian, the Rev. Professor, Ignacy Rózycki. A brief summary of his scholarly and theological work is published under the title The Divine Mercy: Basic Characteristics of the Divine Mercy Devotion.
Compared to this important theological work, all previous publications on the Divine Mercy devotion, related to us by St. Faustina, seem to be concerned only with some of its elements or with more secondary matters. For example, in some instances, emphasis is placed on the Litany or the Novena to The Divine Mercy, leaving aside the Hour of Mercy.
Fr. Rózycki draws our attention to this fact by saying: “Before we acquaint ourselves with the specific elements of the Divine Mercy devotion, we need to notice that among them we won?t find any of the well-known or beloved novenas or litanies.”
The basis for selecting these, and not other prayers or religious practices, as the new forms of the Divine Mercy devotion, are the specified promises attached to them, which the Lord Jesus promised to fulfill on the condition of one?s trust in God?s goodness and of mercy towards one?s neighbors. Rev. Rózycki points out that there are five elements of the devotion to The Divine Mercy.
a. The Image of the Merciful Jesus. Its pattern was revealed in the vision St. Faustina had on February 22, 1931, in her convent cell at Plock. “In the evening, when I was in my cell,” she recorded in the Diary, “I saw the Lord Jesus clothed in a white garment. One hand [was] raised in the gesture of blessing, the other was touching the garment at the breast. From beneath the garment, slightly drawn aside from at breast, there were emanating two large rays, one red, the other pale. …. After a while, Jesus said to me, „Paint an image according to the pattern you see, with the signature: Jesus, I trust in You??? (Diary, 47). “I want this image …… to be solemnly blessed on the first Sunday after Easter; that Sunday is to be the Feast of Mercy” (Diary, 49).
9 ////////////////
For this reason, the content of this image is closely related to the liturgy of that Sunday. On this day, the Church reads the Gospel according to St. John about the risen Christ appearing in the Upper Room and about the institution of the Sacrament of Penance (Jn 20:19-29). Consequently, this image represents the Savior risen from the dead who brings peace to people by means of the forgiveness of sins at the price of His passion and death on the cross.
The rays of blood and water that flow from the Heart that was pierced by a spear (not visible on the image) and the scars caused by the wounds of crucifixion call to mind the events of Good Friday (Jn 19:17-18; 33-37). The Image of the Merciful Savior, therefore, combines the two Gospel events that best bespeak the fullness of God?s love for mankind.
The two rays are a distinctive feature of this image of Christ. The Lord Jesus, when asked about their meaning, explained: “The pale ray stands for the Water which makes souls righteous. The red ray stands for the Blood which is the life of souls. … Happy is the one who will dwell in their shelter” (Diary, 299). The Sacraments of Baptism and Penance purify the soul, and the Eucharist most abundantly nourishes it. Thus, the two rays signify the Holy Sacraments and all the graces of the Holy Spirit, whose biblical symbol is water, as well as the New Covenant of God with men in the Blood of Christ.
The image of the Merciful Jesus is often called the “Image of The Divine Mercy,” which is appropriate, since it is precisely in Christ?s Paschal Mystery that God?s love for humankind was most explicitly revealed.////////////
The image not only represents The Divine Mercy, but also serves as a sign that is to recall the Christian obligation of trust in God and of active love toward neighbor. By Christ?s will the image bears a signature comprised of these words: “Jesus, I trust in You.” “This image,” Jesus also declared, “is to be a reminder of the demands of My mercy, because even the strongest faith is of no avail without works” (Diary, 742).
To the veneration of the image understood in this way, as relying upon the Christian attitude of trust and mercy, Our Lord attached special promises, namely, of eternal salvation, of great progress in the way of Christian perfection, of the grace of a happy death, and of all other possible graces which people will ask of Him with trust: “By means of this Image I shall be granting many graces to souls; so let every soul have access to it” (Diary, 570).
b. The Feast of The Divine Mercy. It ranks highest among all the elements of The Divine Mercy devotion revealed to [St.] Faustina. Its institution was requested by the Lord Jesus for the first time in Plock, in 1931, while He was communicating His will regarding the painting of the Image: “I desire that there be a Feast of Mercy. I want this image, which you will paint with a brush, to be solemnly blessed on the first Sunday after Easter; that Sunday is to be the Feast of Mercy” (Diary, 49).
The choice of the first Sunday after Easter for the Feast of Mercy has a very deep theological significance, which points to the close relationship between the Paschal Mystery of the redemption and the mystery of The Divine Mercy. The integral relationship is further emphasized by the Novena of Chaplets to The Divine Mercy which begins on Good Friday as a preparation for the Feast.
///////////
10
This feast is not only a day in particular for worshipping God in His mystery of mercy, but also a time of grace for all people. The Lord Jesus said: “I desire that the Feast of Mercy be a refuge and shelter for all souls, and especially for poor sinners” (Diary, 699). “Souls perish in spite of My bitter Passion. I am giving them the last hope of salvation, that is, recourse to My Mercy. If they will not adore My mercy, they will perish for all eternity” (cf. Diary, 965, 998).
The greatness of this feast is measured by the measure of extraordinary promises that the Lord attached to this feast: Jesus said “…. Whoever approached the Fount of Life on this day will be granted complete remission of sins and punishment” (Diary, 300), and also, “On this day the very depths of My tender mercy are open. I pour out a whole ocean of graces upon those souls who approach the fount of My Mercy. …… Let no soul fear to draw near to Me, even though its sins be as scarlet” (Diary, 699).
To profit from those great gifts we must fulfill the conditions of the Divine Mercy devotion (trust in God?s goodness and active love toward neighbor), be in the state of sanctifying grace – having gone to Holy Confession, and worthily receive Holy Communion. Jesus explained: “No soul will be justified until it turns with confidence to My mercy; and this is why the first Sunday after Easter is to be the Feast of Mercy, and on that day, priests are to tell everyone about My great and unfathomable mercy” (Diary, 570).
c. The Chaplet of The Divine Mercy. This Chaplet was dictated to St. Faustina by the Lord Jesus Himself in Vilnius on September 13-14, 1935, as a prayer of atonement and for the appeasement of God?s wrath (see Diary, 474-476).  /////////
Those who recite this Chaplet offer to god the Father “the Body and Blood, Soul and Divinity,” of Jesus Christ in atonement for their sins, the sins of their loved ones, and those of the entire world. By uniting themselves with the sacrifice of Jesus, they appeal to the great love that our Heavenly Father has for His Son and, in Him, for all humanity.
By means of this prayer, the petitioners request “mercy on us and on the whole world,” and by so doing, they perform a work of mercy. If the faithful add to this the foundation of trust and fulfill the conditions regarding every good prayer (humility, perseverance, matters in conformity with God’s will), they can expect the fulfillment of Christ’s promises which are particularly related to the hour of death: the grace of conversion and a peaceful death.
Not only will the people who say the Chaplet receive these graces, but also the dying at whose side others will recite this prayer. The Lord said: “When this chaplet is said by the bedside of a dying person, God’s anger is placated, unfathomable mercy envelops the soul” (Diary, 811). The general promise says: “It pleases Me to grant everything they ask of Me by saying the chaplet” (Diary 1541) “….if what you ask for is compatible with My will” (Diary, 1731). For, anything that is not compatible with God’s will is not good for people, especially for their eternal happiness.
On a different occasion, Jesus said: “ by saying the Chaplet, you are bringing humankind closer to Me” (Diary, 929), and again: “The souls that say this chaplet will be embraced by My mercy during their lifetime and especially at the hour of their death” (Diary, 754). </h3>
        
    </section>

    <section class="contact">
        <header>
            <h3>Address:</h3>
        </header>
        <p>
            One Microsoft Way<br />
            Redmond, WA 98052-6399
        </p>
    </section>
</asp:Content>