//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inżynierka
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaneUzytkownikow
    {
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string E_mail { get; set; }
        public string E_mailPotwierdzający { get; set; }
        public string Komentarz { get; set; }
        public int IDUzytkownikow { get; set; }
    }
}
