//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inżynierka
{
    using System;
    using System.Collections.Generic;
    
    public partial class GodzinyRozkladowLotow
    {
        public int IDgodziny { get; set; }
        public string godzinyPoranne { get; set; }
        public string godzinyWieczorne { get; set; }
        public string IDmiasta { get; set; }
        public Nullable<int> IDTypyPołączenia { get; set; }
    
        public virtual MIASTA MIASTA { get; set; }
        public virtual TypyPołączenia TypyPołączenia { get; set; }
    }
}
