//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inżynierka
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIASTA
    {
        public MIASTA()
        {
            this.GodzinyRozkladowLotow = new HashSet<GodzinyRozkladowLotow>();
        }
    
        public string IDmiasta { get; set; }
        public string miasto { get; set; }
    
        public virtual ICollection<GodzinyRozkladowLotow> GodzinyRozkladowLotow { get; set; }
    }
}
