//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inżynierka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemRezerwacjiBiletowEntities5 : DbContext
    {
        public SystemRezerwacjiBiletowEntities5()
            : base("name=SystemRezerwacjiBiletowEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DaneUzytkownikow> DaneUzytkownikow { get; set; }
        public DbSet<GodzinyRozkladowLotow> GodzinyRozkladowLotow { get; set; }
        public DbSet<MiasPrzy> MiasPrzy { get; set; }
        public DbSet<MIASTA> MIASTA { get; set; }
        public DbSet<MiasWylo> MiasWylo { get; set; }
        public DbSet<Parametry> Parametry { get; set; }
        public DbSet<Parametry2> Parametry2 { get; set; }
        public DbSet<TypyPołączenia> TypyPołączenia { get; set; }
    }
}
