//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inżynierka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametry
    {
        public int IDPolaczenia { get; set; }
        public string MiastoWylotu { get; set; }
        public string MiastoPrzylotu { get; set; }
        public Nullable<int> Odleglosc { get; set; }
        public Nullable<int> Cena { get; set; }
        public string Linia { get; set; }
        public string GodzinaWylotu { get; set; }
        public string GodzinaPrzylotu { get; set; }
    }
}
