//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inżynierka
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypyPołączenia
    {
        public TypyPołączenia()
        {
            this.GodzinyRozkladowLotow = new HashSet<GodzinyRozkladowLotow>();
        }
    
        public int IDTypyPołączenia { get; set; }
        public string TypPołączenia { get; set; }
    
        public virtual ICollection<GodzinyRozkladowLotow> GodzinyRozkladowLotow { get; set; }
    }
}
